=== psy-immo/dev/dtd/efml.0.0.1.0.dtd
<!ELEMENT efml (#PCDATA|title|tags|tie|runway|answer|tables|i|b|br)* >

<!ELEMENT br EMPTY >

<!ELEMENT i (#PCDATA|i|b|br)* >

<!ELEMENT b (#PCDATA|i|b|br)* >

<!ELEMENT tags (#PCDATA|tags|tie|runway|answer|tables|i|b|br)* >

<!ATTLIST tags 
	tags	CDATA	#IMPLIED
	atags	CDATA	#IMPLIED
	rtags	CDATA	#IMPLIED
 >

<!ELEMENT tables (#PCDATA|r|c|tags|tie|runway|answer|i|b|br)* >

<!ATTLIST tables 
	tags	CDATA	#IMPLIED
	atags	CDATA	#IMPLIED
	rtags	CDATA	#IMPLIED
 >

<!ELEMENT r EMPTY >

<!ELEMENT c EMPTY >

<!ELEMENT tie (#PCDATA|i|b|br|tags|tie|runway|answer)* >

<!ATTLIST tie 
	tags	CDATA	#IMPLIED
	atags	CDATA	#IMPLIED
	rtags	CDATA	#IMPLIED
 >

<!ELEMENT runway (#PCDATA)* >

<!ATTLIST runway 
	tags	CDATA	#IMPLIED
	atags	CDATA	#IMPLIED
	rtags	CDATA	#IMPLIED

	name	CDATA			#IMPLIED
	content	(respawn|refilling)	#IMPLIED
	color	CDATA			#IMPLIED
	filled	CDATA			#IMPLIED
	width	CDATA			#IMPLIED
	height	CDATA			#IMPLIED
 >

<!ELEMENT answer (#PCDATA|hint|correct|check)* >

<!ATTLIST answer 
	tags	CDATA	#IMPLIED
	atags	CDATA	#IMPLIED
	rtags	CDATA	#IMPLIED
 >

<!ELEMENT hint (#PCDATA|i|b|br)* >

<!ELEMENT correct (#PCDATA|i|b|br)* >

<!ELEMENT check (#PCDATA)* >

=== psy-immo/dev/demo/efml/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE efml SYSTEM "https://raw.github.com/psy-immo/dev/master/dtd/efml.0.0.1.0.dtd">
<efml>
	<tags tags="frage1" atags="frage1">
	
	<div>
	  <p>
	<tables height="75px">
	<r/>Eine<r/><c/><r/>Versuchsbedingung<r/><c/><r/>mit<r/>	
	
	<c/><runway tags="r1,c1"/><r/><runway tags="r2,c1"/><r/><runway tags="r3,c1"/><c/> 
	
	<r/>Intensität<r/><c/><r/>des<r/><c/><r/>CS<r/><c/><r/>führt<r/><c/><r/>im<r/><c/><r/>
	Gegensatz<r/><c/><r/>zu<r/><c/><r/>einer<r/><c/><r/>Versuchsbedingung<r/><c/><r/>mit<r/>
	
	<c/><runway tags="r1,c2"/><r/><runway tags="r2,c2"/><r/><runway tags="r3,c2"/><c/> 
	<r/>Intensität<r/><c/><r/>des<r/><c/><r/>CS<r/><c/><r/>bei<r/><c/><r/>mittlerer<r/><c/><r/>
	Intensität<r/><c/><r/>des<r/><c/><r/>US<r/><c/><r/>schneller<r/><c/><r/>zu<r/><c/><r/>einer
	<r/><c/><r/>erhöhten<r/><c/><r/>Lernrate.<r/>
	
      
	</tables> 
	</p>
	<table style="width: 1000px; " border="0" cellpadding="0" cellspacing="0"><tr><td>
	  <tables height="75px"><runway content="refilling">geringer</runway> 
	  <r/><runway content="refilling">mittlerer</runway> 
	  <r/><runway content="refilling">hoher</runway>
	  </tables>
	</td><td>
	  <table style="width: 400px; " border="0" cellpadding="0" cellspacing="0"><tr><td>
	
	<answer>Antwort prüfen<hint>Das ist leider noch nicht richtig.
	  Versuche es noch einmal!</hint><hint>Das ist leider noch nicht richtig.
	    Lies noch einmal in den Lerntexten nach!</hint><hint>Das ist leider noch nicht richtig.
	     Tipp: Beim klassischen Konditionieren findet Assoziationslernen dadurch statt,
	     dass ein NS mit einem US gepaart wird. Der NS wird so zu einem CS.
	       Daher ist es notwendig, dass der CS nicht zu schwach ist.</hint><correct>Richtig!
	       </correct><check>tag t in "r1" "r2" "r3": field x with t "c1": field y with t "c2":
		 (x = "mittlerer") and (y = "geringer")</check><check>
		   tag t in "r1" "r2" "r3": field x with t "c1": field y with t "c2":
		     (x = "hoher") and (y = "mittlerer")</check><check>
		   tag t in "r1" "r2" "r3": field x with t "c1": field y with t "c2":
		     (x = "hoher") and (y = "geringer")
		 </check></answer>
	       </td></tr></table>
	     </td></tr></table>
	</div>
      
	
	
	</tags>
</efml>
